title: "Христорождественский собор"
# ВАЖНО: Указываем имя репозитория с слэшем в начале
baseurl: "/sobor_Rozhdestva"
url: "https://dmitrii048.github.io"

permalink: /news/:year/:month/:day/:title/

# Включаем плагины (стандарт для GitHub)
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Исключаем лишнее, чтобы не мешало сборке
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
